# Generated by Django 5.2.6 on 2025-09-20 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_art', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_art', models.CharField(max_length=100)),
                ('contenido_art', models.CharField(max_length=250)),
                ('creacion_art', models.DateField()),
                ('actualizacion_art', models.DateField()),
                ('autor_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comen', models.AutoField(primary_key=True, serialize=False)),
                ('contenido_comen', models.CharField(max_length=250)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Blog.articulo')),
                ('autor_comen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
