# Generated by Django 5.2.6 on 2025-09-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='actualizacion_art',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='creacion_art',
            field=models.DateField(auto_now_add=True),
        ),
    ]
