# Generated by Django 5.2.6 on 2025-09-20 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_articulo_actualizacion_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='creacion_comen',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido_art',
            field=models.CharField(max_length=350),
        ),
    ]
